Fix failing build on 2.4 & 2.5
Example failure: https://github.com/pry/pry/runs/3010680604

```
ArgumentError: wrong number of arguments (given 4, expected 1)
    /home/runner/work/pry/pry/vendor/bundle/ruby/2.4.0/gems/psych-4.0.1/lib/psych.rb:323:in `safe_load'
```

I am not sure what exactly causes the failure but deleting simplecov dependency
fixes (I guess?) this problem.