Handle error about frozen object in Ruby 2.2
This kind of error message seems to be updated in Ruby 2.2.

For example, the following code throws an error that has different
error message with Ruby version:
```
"".freeze.instance_eval do
  def hi
  end
end
```

In Ruby 2.1.3:
> RuntimeError: can't modify frozen Class

In Ruby 2.2.0-preview1:
> RuntimeError: can't modify frozen object