fix random test failure
when the tests are run in a certain order spec/completion_spec.rb can fail with:
NameError: uninitialized constant Pry::InputCompleter::Readline
  /Users/giorgio/code/pry/lib/pry/input_completer.rb:6:in `start': Pry::InputCompleter - should not crash if there's a Module that has a symbolic name.
  /Users/giorgio/code/pry/lib/pry/config/default.rb:41:in `block in <class:Default>'
  /Users/giorgio/code/pry/lib/pry/config/default.rb:58:in `instance_eval'

we require readline so we know spec/completion_spec.rb has its dependencies met
before being run.